[package]
name = "yardland"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "^0.2"
once_cell = "^1.18"
num_enum = "^0.7"
bevy = { version = "0.14.1", features = ["dynamic_linking"] }
egui = "0.28.1"
bevy_egui = "0.29.0"

[build-dependencies]
cc = "^1.0"
