[package]
name = "yardland"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_egui = "0.29.0"
once_cell = "1.19.0"
num_enum = "0.7.3"
libc = "0.2.158"

[build-dependencies]
cc = "1.1.19"
